In [1]:
import warnings
warnings.filterwarnings('ignore')

## Numpy

Numpy - библиотека python, позволяющая делать сложные вычисления и операции с массивами.

Главный объект Numpy - это однородный многомерный массив. 

Массив - упорядоченный набор однородных данных, доступных по индексу. Чаще всего это одномерная последовательность или двумерная таблица, заполненные элементами одного типа.

[Подробнее](https://pyprog.pro/introduction.html) о массивах

In [2]:
import numpy as np

In [3]:
a = np.array([1, 3, 2])

a

array([1, 3, 2])

In [4]:
a = np.array([[1.5, 2, 3], [4, 5, 6]], dtype=np.complex128) 
#В отличии от списков, в массиве все элементы обязательно принадлежат одному типу

a

array([[1.5+0.j, 2. +0.j, 3. +0.j],
       [4. +0.j, 5. +0.j, 6. +0.j]])

In [5]:
a = np.array([[1.5, 2, 3], [4, 5, 600000]], dtype=np.int16) #создаст одномерную матрицу размером 2 х 3 c типом данных int16 

a

#Массив будет преобразован в соответствии с данным типом и на выходе полчим следующее:
#Дробные числа переведены в целочисленный формат в соответствии с типом
#Число 600000 не умещается в тип int16, происходит "переполнение типа"


array([[    1,     2,     3],
       [    4,     5, 10176]], dtype=int16)

## Сложение / Вычитание матриц

In [6]:
### Матрица A размера 2x3
A = np.array([[3, 4, 5],
              [1, 1, 1]])

### Матрица B размера 2x3
B = np.array([[5, 5],
              [3, 1]])

### Так как размеры совпадают, можно вычитать и складывать!

In [7]:
A - B 

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

## Умножение матриц

In [8]:
### Матрица A размера 2x3
A = np.array([[3, 4, 5],
              [1, 1, 1]])

### Матрица B размера 3x3
B = np.array([[5, 5, 5],
              [3, 1, 10],
              [4, 4, 12]])

### Так как кол-во строк матрицы A совпадает с кол-вом строк матрицы B,
### Можем умножить A * B

In [10]:
np.dot(A, B)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

## Транспонирование матриц

In [11]:
A = np.array([[3, 4, 5],
              [1, 1, 1]])

In [12]:
A.T

array([[3, 1],
       [4, 1],
       [5, 1]])

## Единичная матрица

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Обращение матриц

In [14]:
### Матрица A размера 3x3 => Ее можно обращать
A = np.array([[5, 5, 5],
              [3, 2, 10],
              [4, 4, 12]])

In [15]:
np.linalg.inv(A)

array([[ 0.4  ,  1.   , -1.   ],
       [-0.1  , -1.   ,  0.875],
       [-0.1  ,  0.   ,  0.125]])

## $\beta^* = (X^T \cdot X)^{-1}\cdot X^T \cdot Y$

In [16]:
X = np.array([[23, 0.5, 1],
              [35, 1, 1],
              [18, 0, 1]])

Y = np.array([55, 100, 45])


In [17]:
xxt = np.dot(X.T, X)
xxt_inv = np.linalg.inv(xxt)
xxt_inv_xxt = np.dot(xxt_inv, X.T)
final_betas = np.dot(xxt_inv_xxt, Y)

final_betas

array([  5., -30., -45.])

## Пример с первого практического занятия

In [18]:
import pandas as pd

X = pd.read_csv('X.csv').drop('Предсказание', axis=1)
Y = pd.read_csv('Y.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'X.csv'

In [ ]:
X.head()

Категория  Цель в долларах  Срок  Год публикации  Close_brent  CAD  CHF  \
0  6035.989239           1000.0    39            2009        34.41    0    0   
1  3591.033473          80000.0    87            2009        34.41    0    0   
2  3661.424550             20.0     8            2009        34.41    0    0   
3  4321.245721             99.0    79            2009        34.41    0    0   
4  6035.989239           1900.0    28            2009        34.41    0    0   

   DKK  EUR  GBP  ...  Design  Fashion  Film & Video  Food  Journalism  Music  \
0    0    0    0  ...       0        1             0     0           0      0   
1    0    0    0  ...       0        0             1     0           0      0   
2    0    0    0  ...       0        0             0     0           0      0   
3    0    0    0  ...       0        0             0     0           0      0   
4    0    0    0  ...       0        1             0     0           0      0   

   Photography  Publishing  Technology  Theater  
0            0           0           0        0  
1            0           0           0        0  
2            0           0           0        0  
3            0           0           1        0  
4            0           0           0        0  

[5 rows x 32 columns]

In [ ]:
Y.head()

таргет2
0    625.0
1     22.0
2     35.0
3    145.0
4    387.0

In [ ]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X, Y)


for column, coef in zip(X.columns, model.coef_):
    print(column, coef)
    
print(model.intercept_)

Категория 0.9912323981302028
Цель в долларах 0.00046210545732411
Срок 84.7960380387574
Год публикации 789.623759578069
Close_brent 32.52363238751121
CAD 477.0442389583962
CHF 8787.42593334129
DKK 519.7524602299042
EUR 408.436698789295
GBP 2794.5137779940305
HKD -2352.9318103890287
JPY -8944.518338941747
MXN -4246.631441116689
NOK -1181.5007050675156
NZD -395.7721892123315
SEK 2085.2689875865517
SGD -1612.7741094312478
USD 7000.650258232897
Art -105.3700874282956
Comics -531.3510093663201
Crafts -608.7810292957257
Dance -379.446410488763
Design -219.11835083464044
Fashion -293.370137548206
Film & Video -49.87838409990245
Food -692.236001794821
Journalism -451.5810021298357
Music -303.9350860455762
Photography 222.96861493755802
Publishing -370.53746498403916
Technology -175.9808894795485
Theater 237.6083627399823
[-1600008.97574461]


In [ ]:
X['constant'] = 1

In [ ]:
xxt = np.dot(X.T, X)
xxt_inv = np.linalg.inv(xxt)
xxt_inv_xxt = np.dot(xxt_inv, X.T)
final_betas = np.dot(xxt_inv_xxt, Y)

final_betas

array([[ 9.91232399e-01],
       [ 4.62105457e-04],
       [ 8.47960380e+01],
       [ 7.89623760e+02],
       [ 3.25236324e+01],
       [ 4.77044239e+02],
       [ 8.78742593e+03],
       [ 5.19752460e+02],
       [ 4.08436699e+02],
       [ 2.79451378e+03],
       [-2.35293181e+03],
       [-8.94451834e+03],
       [-4.24663144e+03],
       [-1.18150071e+03],
       [-3.95772189e+02],
       [ 2.08526899e+03],
       [-1.61277411e+03],
       [ 7.00065026e+03],
       [-1.05370087e+02],
       [-5.31351009e+02],
       [-6.08781029e+02],
       [-3.79446410e+02],
       [-2.19118351e+02],
       [-2.93370138e+02],
       [-4.98783841e+01],
       [-6.92236002e+02],
       [-4.51581002e+02],
       [-3.03935086e+02],
       [ 2.22968615e+02],
       [-3.70537465e+02],
       [-1.75980889e+02],
       [ 2.37608363e+02],
       [-1.60000898e+06]])

In [ ]:
for column, coef in zip(X.columns, final_betas):
    print(column, coef)

Категория [0.9912324]
Цель в долларах [0.00046211]
Срок [84.796038]
Год публикации [789.62375955]
Close_brent [32.52363239]
CAD [477.04423896]
CHF [8787.42593335]
DKK [519.75246024]
EUR [408.4366988]
GBP [2794.513778]
HKD [-2352.9318104]
JPY [-8944.51833898]
MXN [-4246.63144111]
NOK [-1181.50070505]
NZD [-395.77218921]
SEK [2085.2689876]
SGD [-1612.77410944]
USD [7000.65025821]
Art [-105.37008743]
Comics [-531.35100937]
Crafts [-608.78102928]
Dance [-379.4464105]
Design [-219.11835083]
Fashion [-293.37013754]
Film & Video [-49.87838412]
Food [-692.23600179]
Journalism [-451.58100212]
Music [-303.93508606]
Photography [222.96861493]
Publishing [-370.53746499]
Technology [-175.98088947]
Theater [237.60836272]
constant [-1600008.97568207]


## А что, если данных, в т.ч. признаков, очень много?

In [ ]:
matrix = np.random.rand(50000, 50000)

In [ ]:
matrixdot = np.dot(matrix.T, matrix)
matrix_inv = np.linalg.inv(matrixdot)