In [1]:
import pandas as pd

Загрузим табличку с нашими данными про длительность поездок такси! 

In [2]:
df = pd.read_csv('taxi_dataset_with_target.csv', index_col=0)

df.head()

vendor_id      pickup_datetime  passenger_count  \
id                                                           
id2875421          1  2016-03-14 17:24:55       930.399753   
id2377394          0  2016-06-12 00:43:35       930.399753   
id3858529          1  2016-01-19 11:35:24       930.399753   
id3504673          1  2016-04-06 19:32:31       930.399753   
id2181028          1  2016-03-26 13:30:55       930.399753   

           store_and_fwd_flag  trip_duration  distance_km  
id                                                         
id2875421                   0          455.0     1.500479  
id2377394                   0          663.0     1.807119  
id3858529                   0         2124.0     6.392080  
id3504673                   0          429.0     1.487155  
id2181028                   0          435.0     1.189925

Попробуем построить модель Линейной Регрессии!

В качестве Выборки используйте таргетную колонку (*trip_duration*) и все признаки, кроме времени начала заказа (*pickup_datetime*)

Для начала воспользуемся "коробочным решением". Для этого создайте переменную model, положите в нее класс **LinearRegression** из модуля **linear_model** библиотеки **sklearn**.

Далее воспользуйтесь методом **fit**, положите в него через запятую: массив **X**, состоящий из признаков объектов (можно pandas dataframe'ом, а можно numpy-массивом), и массив **Y** с таргетами.

Чтобы посмотреть на значения полученных коэффициентов модели, следует обратиться к атрибуту **coef\_** класса линейной регрессии. Для просмотра свободного веса, к атрибуту **intercept\_**

---

Полученные коэффициенты будут являться ответом на задание. Перечислите коэффициенты через запятую и пробел, округлив до 3 знаков после точки. Используйте точку в качестве десятичного разделителя.

Пример ответа: `123.231, 0.543, 23.345, 12.433, 120.321`

В этом задании нужно построить модель линейной регрессии. Для этого необходимо:

1. Создать два датафрейма (numpy-массива):
    - X — с признаками (все признаки, кроме pickup\_datetime и trip\_duration)
    - Y — c таргетом (trip\_duration).
2. Создать переменную model, положить в нее класс LinearRegression из модуля linear\_model библиотеки sklearn.
3. Через запятую положить в метод fit созданные ранее датафреймы.
4. Узнать коэффициенты модели и свободный вес, используя model.coef\_ и model.intercept\_.

In [6]:
from sklearn.linear_model import LinearRegression
import numpy as np

# Создаем два массива NumPy: X и Y
X = df.drop(['trip_duration','pickup_datetime'],axis = 1)
Y = df['trip_duration']

# Создаем объект линейной регрессии
model = LinearRegression()

# Обучаем модель
model.fit(X, Y)

# Получаем коэффициенты линейной регрессии и свободный вес
coef = model.coef_
intercept = model.intercept_

Чтобы посмотреть на значения полученных коэффициентов модели, следует обратиться к атрибуту **coef_** класса линейной регрессии. Для просмотра свободного веса, к атрибуту **intercept_** 

np.around is a NumPy function that rounds an array of floating-point numbers to the nearest integer. It has the signature np.around(arr, decimals=0) where arr is the input array and decimals is an optional argument that specifies the number of decimal places to round to. If decimals is not provided, the array is rounded to the nearest integer.

In [9]:
np.around(coef, decimals = 3)


array([198.463,   0.296,  56.469, 115.274])

In [10]:
np.around(intercept, decimals = 3)

171.657

In [1]:
### Полученные коэффициенты будут являться ответом на задание 5 в ЛМС.
### Перечислите коэффициенты через запятую и пробел, округлив до 3 знаков после точки.
### Используйте точку в качестве десятичного разделителя.

Теперь реализуйте функцию LinearRegressionByMatrix, которая будет принимать на вход 3 параметра:

Матрицу объект-признак **(X)**, вектор с ответами **(Y)**, булевый параметр **fit_intercept**, цель которого - добавить константный признак (состоящий из единичек), если True, и ничего не делать, если False.

Функция должна вернуть одномерный np.array объект с оцененными **$\beta_1, ..., \beta_n, \beta_0$**

Реализуйте решение через аналитическое решение в матрицах из лекции и практики:

$$
\beta^* = (X^T \cdot X)^{-1} \cdot X^T \cdot Y
$$

In [4]:
import numpy as np

### Your code is here

def LinearRegressionByMatrix(X: np.array, Y: np.array, fit_intercept: bool = True):
        """
        :param X: матрица объектов
        :param Y: вектор (матрица с 1 столбцом) ответов
        :param fit_intercept: добавить ли константную переменную в данные?
        
        :return: одномерный numpy-array с полученными коэффициентами beta
        """
        
        return 

In [16]:
import numpy as np

def LinearRegressionByMatrix(X, Y, fit_intercept=True):
    
    # Добавляем столбец из единиц, если fit_intercept=True
    if fit_intercept:
        X = np.column_stack((np.ones(X.shape[0]), X))
    
    # Возвращаем решение нормального уравнения
    return np.linalg.inv(X.T @ X) @ X.T @ Y


In [18]:
X_train = df.drop(['trip_duration', 'pickup_datetime'], axis=1).values
Y_train = df['trip_duration'].values

LinearRegressionByMatrix(X_train, Y_train)

array([171.65658145, 198.46313674,   0.29631295,  56.46912165,
       115.27353763])

In [19]:
import numpy as np

def LinearRegressionByMatrix(X, Y, fit_intercept=True):
    if fit_intercept:
        X = np.column_stack((np.ones(X.shape[0]), X))
    beta_star = np.linalg.inv(X.T @ X) @ X.T @ Y
    
    # Возвращаем строку с коэффициентами, разделенными пробелами
    return ' '.join([str(round(beta, 3)) for beta in beta_star])


In [20]:
X_train = df.drop(['trip_duration', 'pickup_datetime'], axis=1).values
Y_train = df['trip_duration'].values

LinearRegressionByMatrix(X_train, Y_train)

'171.657 198.463 0.296 56.469 115.274'

In [5]:
### Полученные коэффициенты будут являться ответом на задание 6 в ЛМС.
### Перечислите коэффициенты через запятую и пробел, округлив в большую сторону до 3 знаков после точки.
### Используйте точку в качестве десятичного разделителя.

Получились ли коэффициенты такими же, как и в "коробочном" варианте?

Имея коэффициенты модели, можно восстановить предсказания для каждого объекта!

Сделайте это через операцию матричного произведения матрицы **X** и полученных коэффициентов (как результат работы *LinearRegressionByMatrix*)

numpy.linalg.inv is a function in the NumPy library for Python which is used to calculate the (multiplicative) inverse of a matrix. The inverse of a matrix A is a matrix A^-1 such that A * A^-1 = I (where I is the identity matrix), i.e., it "undoes" the linear transformation represented by A. The inverse is not defined for singular matrices (i.e., matrices that do not have an inverse).

In [23]:
beta_star = np.linalg.inv(X.T @ X) @ X.T @ Y

In [24]:
Final = np.dot(X,beta_star)
Final

array([ 811.35584722,  651.84964688, 1375.45281398, ..., 1541.61345327,
        569.58841681,  574.3934665 ])

In [29]:
df['trip_duration'].values

array([ 455.,  663., 2124., ...,  764.,  373.,  198.])

In [32]:
# Calculate the mean squared error
mse = np.mean((Y - Final) ** 2)
print("Mean Squared Error: ", mse)

Mean Squared Error:  27173452.726003308


In [35]:
import numpy as np

# Define the matrix
A = np.array([[1, 2], [3, 4]])

# Calculate the inverse of the matrix
A_inv = np.linalg.inv(A)

print("Matrix A:")
print(A)

print("\nInverse of matrix A:")
print(A_inv)

print("\nCheck: A * A_inv")
print(np.dot(A, A_inv))


Matrix A:
[[1 2]
 [3 4]]

Inverse of matrix A:
[[-2.   1. ]
 [ 1.5 -0.5]]

Check: A * A_inv
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [37]:
print(X_train)

[[  1.         930.39975328   0.           1.50047895]
 [  0.         930.39975328   0.           1.80711941]
 [  1.         930.39975328   0.           6.39208025]
 ...
 [  1.         930.39975328   0.           7.83295239]
 [  0.         930.39975328   0.           1.09378613]
 [  0.         930.39975328   0.           1.13545341]]


y=198.463⋅x1​+0.296⋅x2​+56.469⋅x3​+115.274⋅x4​+171.657