# Введение. Полносвязные слои. Функции активации (ноутбук)

> Начнем осваивать библиотеку `PyTorch`. Познакомимся с нейронными сетями.

## План ноутбука

1. Установка `PyTorch`
1. Введение в `PyTorch`
1. Полносвязные слои и функции активации в `PyTorch`
1. Градиентный спуск своими руками

## Установка `PyTorch`

Мы будем использовать библиотеку для глубинного обучения `PyTorch`, ее можно не устанавливать, будем пользоваться сайтом [kaggle.com](kaggle.com) для обучения в облаке (или с учителем?). 

Чтобы установить `PyTorch` локально себе на компьютер нужно ответить на два вопроса - какая у вас операционная система и есть ли у вас дискретная видеокарта (GPU) и если есть, то какого производителя. В зависимости от ваших ответов мы получаем три варианта по операционной системе - Linux, Mac и Windows; три варианта по дискретной видеокарте - нет видеокарты (доступен только центральный процессор CPU), есть видеокарта от Nvidia или есть видеокарта от AMD (это производитель именно чипа, конечный вендор может быть другой, например, ASUS, MSI, Palit). Работа с PyTorch с видеокартой от AMD это экзотика, которая выходит за рамки нашего курса, поэтому рассмотрим только варианты *нет видеокарты*/*есть видеокарта от Nvidia*.


Выберите на [сайте](https://pytorch.org/get-started/locally/) подходящие вам варианты операционной системы/видеокарты и скопируйте команду для установки. Разберем подробно самые популярные варианты установки:

### Установка в Linux ([поддерживаемые дистрибутивы](https://pytorch.org/get-started/locally/#supported-linux-distributions))

На линуксе будет работать поддержка `PyTorch` в любой конфигурации, что у вас нет видеокарты, что есть от Nvidia, что от AMD. 

Пререквизит для работы с видеокартой от Nvidia - нужно поставить CUDA, это инструмент от компании Nvidia, который позволяет ускорять вычисления на их же ГПУ. Чтобы поставить себе на машину все правильно воспользуйтесь этим [гайдом](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html) от Nvidia.

 - **pip**

`pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu` для тех, у кого нет видеокарты.

`pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116` для тех, у кого есть видеокарта (либо другой `--extra-index-url`, смотрите на сайте PyTorch, в зависимости от версии CUDA).

 - **conda**

`conda install pytorch torchvision torchaudio cpuonly -c pytorch` для тех, у кого нет видеокарты.

`conda install pytorch torchvision torchaudio cudatoolkit=11.6 -c pytorch -c conda-forge` для тех, у кого есть видеокарта (либо немного другая команда, в зависимости от версии CUDA).

### Установка в Windows

На винде будет работать поддержка `PyTorch` только для видеокарт от Nvidia и без видеокарт вообще. 

Пререквизит для работы с видеокартой от Nvidia - нужно поставить CUDA, это инструмент от компании Nvidia, который позволяет ускорять вычисления на их же ГПУ. Чтобы поставить себе на машину все правильно воспользуйтесь этим [гайдом](https://docs.nvidia.com/cuda/cuda-installation-guide-microsoft-windows/index.html) от Nvidia.

 - **pip**

`pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu` для тех, у кого нет видеокарты.

`pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116` для тех, у кого есть видеокарта (либо другой `--extra-index-url`, смотрите на сайте PyTorch, в зависимости от версии CUDA).

 - **conda**

`conda install pytorch torchvision torchaudio cpuonly -c pytorch` для тех, у кого нет видеокарты.

`conda install pytorch torchvision torchaudio cudatoolkit=11.6 -c pytorch -c conda-forge` для тех, у кого есть видеокарта (либо немного другая команда, в зависимости от версии CUDA).



### Установка на Mac

На маках есть пока что поддержка `PyTorch` только центрального процессора, чуть позже появится поддержка ускорения на чипах M1, M2, M1 Pro и так далее.

 - **pip**

`pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu` 

 - **conda**

`conda install pytorch torchvision torchaudio cpuonly -c pytorch`

## Введение в `PyTorch`

### Тензоры

Тензоры — это специализированная структура данных, по сути это массивы и матрицы. Тензоры очень похожи на массивы в numpy, так что, если у вас хорошо с numpy, то разобраться в PyTorch тензорах будет очень просто. В PyTorch мы используем тензоры для кодирования входных и выходных данных модели, а также параметров модели.

In [1]:
import torch
import numpy as np

### Создание тензоров

Тензор можно создать напрямую из каких-то данных - нам подходят все списки с числами:

In [2]:
some_data = [1, 2, 3, 4]
some_tensor = torch.tensor(some_data)

some_tensor

tensor([1, 2, 3, 4])

In [3]:
some_data = [[1, 2], [3, 4], [5, 6]]
some_tensor = torch.tensor(some_data)

some_tensor

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [4]:
some_data = [[[1], [2]], [[3], [4]], [[5], [6]]]
some_tensor = torch.tensor(some_data)

some_tensor

tensor([[[1],
         [2]],

        [[3],
         [4]],

        [[5],
         [6]]])

На самом деле про "все" списки с числами - обман. Если у вашего списка есть какой-то уровень вложенности, то должны совпадать размерности у всех вложенных списков (подробнее про размерности поговорим позже):

In [5]:
some_other_data = [[1, 2], [3, 4], [5, 6, 7]]
some_other_tensor = torch.tensor(some_other_data)

some_other_tensor

ValueError: expected sequence of length 2 at dim 1 (got 3)

Также тензоры можно создавать из numpy массивов и наоборот:

In [6]:
some_numpy_array = np.array(some_data)

some_numpy_array

array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]]])

In [8]:
some_tensor_from_numpy = torch.from_numpy(some_numpy_array)

some_tensor_from_numpy

tensor([[[1],
         [2]],

        [[3],
         [4]],

        [[5],
         [6]]], dtype=torch.int32)

При этом если мы создаем тензор из numpy массива с помощью `torch.from_numpy`, то они делят между собой память, где лежат их данные и, соответственно, при изменении тензора меняется numpy массив и наоборот:

In [9]:
x = np.ones(10)
y = torch.from_numpy(x)

x, y

(array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=torch.float64))

In [10]:
x += 1

x, y

(array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]),
 tensor([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.], dtype=torch.float64))

In [11]:
x = torch.ones(10)
y = x.numpy()

x, y

(tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [12]:
x += 1

x, y

(tensor([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]),
 array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.], dtype=float32))

Можем создать тензор со случайными или константными значениями:

In [13]:
shape = (2, 3)

random_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
empty_tensor = torch.empty(shape)

random_tensor, ones_tensor, zeros_tensor, empty_tensor

(tensor([[0.1912, 0.9945, 0.4320],
         [0.4410, 0.3055, 0.4617]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[5.3137e-08, 1.2801e-11, 3.2540e+21],
         [2.0315e+20, 2.0971e-07, 2.5230e-09]]))

Теперь поговорим про размерности подробнее.

У тензора есть какой-то размер, какая форма. Первое с чем нужно определиться, какой **размерности** тензор - количество осей у него.

In [14]:
shape = (10)  # одна ось (вектор)

tensor = torch.rand(shape)

tensor

tensor([0.3589, 0.4420, 0.0275, 0.5204, 0.3438, 0.7615, 0.2045, 0.3488, 0.5234,
        0.1249])

In [15]:
shape = (2, 3)  # две оси (матрица)

tensor = torch.rand(shape)

tensor

tensor([[0.0580, 0.5991, 0.4891],
        [0.7393, 0.9290, 0.5490]])

In [16]:
shape = (3, 2, 3)  # три оси (и больше - тензор)

tensor = torch.rand(shape)

tensor

tensor([[[0.4323, 0.2534, 0.0997],
         [0.9366, 0.3577, 0.0989]],

        [[0.7847, 0.9679, 0.6405],
         [0.5522, 0.6875, 0.3443]],

        [[0.9040, 0.1846, 0.4654],
         [0.9122, 0.9842, 0.8802]]])

Тензор с размерностью 1 - это просто вектор, список чисел.

Тензор с размерностью 2 - это просто матрица, то есть список списков чисел.

Тензор с размерностью 3 и больше - это тензор, то есть список списков списков ... чисел.

Получить доступ к размеру уже созданного тензора - метод `.shape`:

In [17]:
some_data = [[[1], [2]], [[3], [4]], [[5], [6]]]
some_tensor = torch.tensor(some_data)

print(some_tensor)
print(some_tensor.shape)

tensor([[[1],
         [2]],

        [[3],
         [4]],

        [[5],
         [6]]])
torch.Size([3, 2, 1])


В лекции мы говорили про изображения, давайте сделаем тензор, который будет нам имитировать изображение - сделаем его размер `(c, h, w)`, где `h` и `w` это его высота и ширина, а `c` - число каналов в цветовом пространстве (в черно-белом 1, в RGB 3):

In [18]:
h = 9
w = 16
c = 3

shape = (c, h, w)

image_tensor = torch.rand(shape)

image_tensor

tensor([[[5.5065e-01, 6.3749e-01, 5.6489e-01, 4.1040e-01, 3.8251e-01,
          9.0649e-01, 2.7085e-01, 7.2695e-01, 4.1717e-02, 6.9695e-01,
          5.6163e-01, 6.3981e-01, 1.9839e-01, 3.8246e-01, 4.2399e-01,
          4.8876e-01],
         [9.1767e-02, 6.6617e-01, 2.0268e-01, 4.1912e-02, 7.6421e-02,
          8.4394e-01, 9.3419e-01, 2.4331e-02, 7.1487e-01, 2.0309e-01,
          6.8665e-05, 2.6198e-01, 1.9354e-01, 1.6518e-01, 7.4314e-01,
          4.5664e-01],
         [2.9842e-01, 9.9818e-01, 5.7447e-01, 9.6147e-01, 1.4426e-01,
          3.5030e-01, 2.1674e-02, 4.3049e-01, 4.5182e-01, 2.5391e-01,
          9.4792e-01, 2.6867e-01, 4.5384e-02, 2.8194e-02, 7.2448e-01,
          5.3086e-01],
         [7.0636e-01, 2.4701e-01, 3.0313e-01, 5.3504e-01, 2.1272e-01,
          5.7130e-01, 1.7485e-01, 6.9039e-01, 5.9262e-02, 9.1264e-02,
          8.0106e-02, 5.5693e-01, 2.3414e-01, 1.4344e-02, 2.2960e-01,
          1.0149e-01],
         [1.7792e-01, 8.4268e-01, 5.8148e-02, 1.4533e-01, 9.2825e-01

In [19]:
image_tensor.shape

torch.Size([3, 9, 16])

Можем попробовать поменять размер тензора, например, [вытянуть его в вектор](https://pytorch.org/docs/stable/generated/torch.ravel.html):

In [20]:
image_tensor.ravel()

tensor([5.5065e-01, 6.3749e-01, 5.6489e-01, 4.1040e-01, 3.8251e-01, 9.0649e-01,
        2.7085e-01, 7.2695e-01, 4.1717e-02, 6.9695e-01, 5.6163e-01, 6.3981e-01,
        1.9839e-01, 3.8246e-01, 4.2399e-01, 4.8876e-01, 9.1767e-02, 6.6617e-01,
        2.0268e-01, 4.1912e-02, 7.6421e-02, 8.4394e-01, 9.3419e-01, 2.4331e-02,
        7.1487e-01, 2.0309e-01, 6.8665e-05, 2.6198e-01, 1.9354e-01, 1.6518e-01,
        7.4314e-01, 4.5664e-01, 2.9842e-01, 9.9818e-01, 5.7447e-01, 9.6147e-01,
        1.4426e-01, 3.5030e-01, 2.1674e-02, 4.3049e-01, 4.5182e-01, 2.5391e-01,
        9.4792e-01, 2.6867e-01, 4.5384e-02, 2.8194e-02, 7.2448e-01, 5.3086e-01,
        7.0636e-01, 2.4701e-01, 3.0313e-01, 5.3504e-01, 2.1272e-01, 5.7130e-01,
        1.7485e-01, 6.9039e-01, 5.9262e-02, 9.1264e-02, 8.0106e-02, 5.5693e-01,
        2.3414e-01, 1.4344e-02, 2.2960e-01, 1.0149e-01, 1.7792e-01, 8.4268e-01,
        5.8148e-02, 1.4533e-01, 9.2825e-01, 2.8619e-01, 4.2691e-01, 7.1047e-01,
        1.3794e-01, 2.6083e-01, 2.5526e-

In [21]:
image_tensor.ravel().shape

torch.Size([432])

In [22]:
h * w * c

432

Посчитаем количество элементов в тензоре с помощью [специальной функции](https://pytorch.org/docs/stable/generated/torch.numel.html):

In [23]:
image_tensor.numel()

432

In [24]:
h = 2
w = 3
c = 3

shape = (c, h, w)

image_tensor = torch.rand(shape)

image_tensor

tensor([[[0.5402, 0.3633, 0.7560],
         [0.5026, 0.3691, 0.4226]],

        [[0.2304, 0.1036, 0.1841],
         [0.5608, 0.4025, 0.4875]],

        [[0.8159, 0.3444, 0.0381],
         [0.3014, 0.5945, 0.9387]]])

Попробуем поменять размер с помощью функции [reshape](https://pytorch.org/docs/stable/generated/torch.reshape.html#torch.reshape):

In [25]:
image_tensor.reshape(c, h * w)

tensor([[0.5402, 0.3633, 0.7560, 0.5026, 0.3691, 0.4226],
        [0.2304, 0.1036, 0.1841, 0.5608, 0.4025, 0.4875],
        [0.8159, 0.3444, 0.0381, 0.3014, 0.5945, 0.9387]])

Попробуем собрать из нескольких тензоров один большой:

[torch.cat](https://pytorch.org/docs/stable/generated/torch.cat.html#torch.cat)

In [26]:
x = torch.randn(2, 3)

In [27]:
x

tensor([[-1.4081, -0.1584,  0.1262],
        [ 1.2818,  0.4380, -0.2734]])

In [28]:
torch.cat((x, x, x), dim=0)

tensor([[-1.4081, -0.1584,  0.1262],
        [ 1.2818,  0.4380, -0.2734],
        [-1.4081, -0.1584,  0.1262],
        [ 1.2818,  0.4380, -0.2734],
        [-1.4081, -0.1584,  0.1262],
        [ 1.2818,  0.4380, -0.2734]])

In [29]:
torch.cat((x, x, x), dim=1)

tensor([[-1.4081, -0.1584,  0.1262, -1.4081, -0.1584,  0.1262, -1.4081, -0.1584,
          0.1262],
        [ 1.2818,  0.4380, -0.2734,  1.2818,  0.4380, -0.2734,  1.2818,  0.4380,
         -0.2734]])

In [30]:
x = torch.randn(3, 3)
y = torch.randn(5, 3)
z = torch.randn(1, 3)

for tensor in [x, y, z]:
    print(tensor)

torch.cat((x, y, z), dim=0)

tensor([[-1.5554e+00,  9.6247e-01, -5.0852e-01],
        [-1.1485e+00,  2.9893e-01,  3.1158e-01],
        [-2.0600e-01, -2.6704e+00, -4.1880e-04]])
tensor([[ 1.0418,  1.2733, -0.1258],
        [-0.8262, -0.7864, -0.3093],
        [ 0.6579, -3.0240,  1.3560],
        [-1.5537, -1.4683, -1.3890],
        [-0.4021, -0.1294, -0.4719]])
tensor([[-1.6368, -0.0777, -0.6602]])


tensor([[-1.5554e+00,  9.6247e-01, -5.0852e-01],
        [-1.1485e+00,  2.9893e-01,  3.1158e-01],
        [-2.0600e-01, -2.6704e+00, -4.1880e-04],
        [ 1.0418e+00,  1.2733e+00, -1.2578e-01],
        [-8.2623e-01, -7.8645e-01, -3.0926e-01],
        [ 6.5789e-01, -3.0240e+00,  1.3560e+00],
        [-1.5537e+00, -1.4683e+00, -1.3890e+00],
        [-4.0214e-01, -1.2941e-01, -4.7194e-01],
        [-1.6368e+00, -7.7666e-02, -6.6015e-01]])

In [31]:
x = torch.randn(2, 3)
y = torch.randn(2, 5)
z = torch.randn(2, 1)

for tensor in [x, y, z]:
    print(tensor)

torch.cat((x, y, z), dim=1)

tensor([[-1.0276, -1.0269,  0.2551],
        [ 0.5838, -0.8767,  0.8825]])
tensor([[ 0.7434,  0.2519, -0.7274, -0.1589,  1.0437],
        [ 1.6179,  0.5177, -0.0426,  0.1303,  0.1158]])
tensor([[-0.0690],
        [-0.1560]])


tensor([[-1.0276, -1.0269,  0.2551,  0.7434,  0.2519, -0.7274, -0.1589,  1.0437,
         -0.0690],
        [ 0.5838, -0.8767,  0.8825,  1.6179,  0.5177, -0.0426,  0.1303,  0.1158,
         -0.1560]])

Теперь добавим дополнительную ось:

[torch.unsqueeze](https://pytorch.org/docs/stable/generated/torch.unsqueeze.html)

In [32]:
x = torch.rand(2, 3)

print(x)
print()
print(x.unsqueeze(0), x.unsqueeze(0).shape)
print()
print(x.unsqueeze(1), x.unsqueeze(1).shape)
print()
print(x.unsqueeze(2), x.unsqueeze(2).shape)

tensor([[0.1495, 0.7940, 0.0920],
        [0.7541, 0.2311, 0.5964]])

tensor([[[0.1495, 0.7940, 0.0920],
         [0.7541, 0.2311, 0.5964]]]) torch.Size([1, 2, 3])

tensor([[[0.1495, 0.7940, 0.0920]],

        [[0.7541, 0.2311, 0.5964]]]) torch.Size([2, 1, 3])

tensor([[[0.1495],
         [0.7940],
         [0.0920]],

        [[0.7541],
         [0.2311],
         [0.5964]]]) torch.Size([2, 3, 1])


Уберем лишние оси (где размер единичка):

In [33]:
x = torch.rand(1, 2, 1, 3)

print(x)
print()
print(x.squeeze(), x.squeeze().shape)
print()
print(x.squeeze(0), x.squeeze(0).shape)

tensor([[[[0.1542, 0.6394, 0.4837]],

         [[0.0710, 0.3198, 0.6776]]]])

tensor([[0.1542, 0.6394, 0.4837],
        [0.0710, 0.3198, 0.6776]]) torch.Size([2, 3])

tensor([[[0.1542, 0.6394, 0.4837]],

        [[0.0710, 0.3198, 0.6776]]]) torch.Size([2, 1, 3])


Теперь поговорим про типы данных в тензорах. По умолчанию в тензорах лежат числа в torch.float32 для вещественных и torch.int64 для целочисленных.

In [34]:
tensor = torch.tensor([1.5, 2.2, 3.7, 4.9])

tensor

tensor([1.5000, 2.2000, 3.7000, 4.9000])

In [35]:
tensor.dtype

torch.float32

In [36]:
tensor = torch.tensor([1.5, 2.2, 3.7, 4.9], dtype=torch.float16)

tensor

tensor([1.5000, 2.1992, 3.6992, 4.8984], dtype=torch.float16)

In [37]:
tensor = torch.tensor([1.5, 2.2, 3.7, 4.9], dtype=torch.float64)

tensor

tensor([1.5000, 2.2000, 3.7000, 4.9000], dtype=torch.float64)

In [38]:
tensor = torch.tensor([15, 22, 37, 49])

tensor

tensor([15, 22, 37, 49])

In [39]:
tensor.dtype

torch.int64

In [40]:
tensor = torch.tensor([15, 22, 37, 49], dtype=torch.int32)

tensor

tensor([15, 22, 37, 49], dtype=torch.int32)

In [41]:
tensor = torch.tensor([15, 22, 37, 49], dtype=torch.int16)

tensor

tensor([15, 22, 37, 49], dtype=torch.int16)

Размещение тензора на GPU:

In [57]:
print(torch.cuda.is_available())
print(torch.cuda.get_device_name())

False


AssertionError: Torch not compiled with CUDA enabled

In [47]:
! nvidia-smi

Wed Apr 19 18:13:00 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 531.61                 Driver Version: 531.61       CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                      TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3080       WDDM | 00000000:01:00.0  On |                  N/A |
| 57%   48C    P0              103W / 370W|   1751MiB / 10240MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [48]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')

print(device)

cpu


In [ ]:
tensor = torch.tensor([15, 22, 37, 49], device=device)

tensor

tensor([15, 22, 37, 49], device='cuda:0')

In [ ]:
tensor = torch.tensor([15, 22, 37, 49])

print(tensor)

tensor = tensor.to(device)

tensor

tensor([15, 22, 37, 49])


tensor([15, 22, 37, 49], device='cuda:0')

In [ ]:
tensor.to(torch.int32)

tensor([15, 22, 37, 49], device='cuda:0', dtype=torch.int32)

In [ ]:
tensor = tensor.cpu()

tensor

tensor([15, 22, 37, 49])

In [ ]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)

a + b

tensor([[0.7184, 0.5498, 0.5604],
        [0.4750, 1.2123, 0.9842]])

In [ ]:
a = a.to(device)

a + b

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

In [ ]:
b = b.to(device)

a + b

tensor([[0.7184, 0.5498, 0.5604],
        [0.4750, 1.2123, 0.9842]], device='cuda:0')

### Операции с тензорами

Большая часть операций с тензорами хорошо описана в их [документации](https://pytorch.org/docs/stable/torch.html), разберем основные:

In [ ]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)

a, b

(tensor([[0.0542, 0.3823, 0.5019],
         [0.7535, 0.0122, 0.9364]]),
 tensor([[0.9840, 0.0882, 0.7651],
         [0.7870, 0.4985, 0.0727]]))

In [ ]:
# поэлементные

print(a + b)

print()

print(torch.add(a, b))

print()

print(a.add(b))

tensor([[1.0383, 0.4705, 1.2670],
        [1.5404, 0.5107, 1.0090]])

tensor([[1.0383, 0.4705, 1.2670],
        [1.5404, 0.5107, 1.0090]])

tensor([[1.0383, 0.4705, 1.2670],
        [1.5404, 0.5107, 1.0090]])


In [ ]:
print(a - b)

print()

print(torch.sub(a, b))

print()

print(a.sub(b))

tensor([[-0.9298,  0.2940, -0.2632],
        [-0.0335, -0.4864,  0.8637]])

tensor([[-0.9298,  0.2940, -0.2632],
        [-0.0335, -0.4864,  0.8637]])

tensor([[-0.9298,  0.2940, -0.2632],
        [-0.0335, -0.4864,  0.8637]])


In [ ]:
print(a * b)

print()

print(torch.mul(a, b))

print()

print(a.mul(b))

tensor([[0.0534, 0.0337, 0.3840],
        [0.5929, 0.0061, 0.0680]])

tensor([[0.0534, 0.0337, 0.3840],
        [0.5929, 0.0061, 0.0680]])

tensor([[0.0534, 0.0337, 0.3840],
        [0.5929, 0.0061, 0.0680]])


In [ ]:
print(a / b)

print()

print(torch.div(a, b))

print()

print(a.div(b))

tensor([[ 0.0551,  4.3328,  0.6560],
        [ 0.9574,  0.0244, 12.8874]])

tensor([[ 0.0551,  4.3328,  0.6560],
        [ 0.9574,  0.0244, 12.8874]])

tensor([[ 0.0551,  4.3328,  0.6560],
        [ 0.9574,  0.0244, 12.8874]])


In [ ]:
a = torch.rand(2, 3)
b = torch.rand(3, 4)
c = torch.rand(5, 5)

a, b, c

(tensor([[0.9952, 0.3948, 0.6624],
         [0.8935, 0.0395, 0.9213]]),
 tensor([[0.2513, 0.2235, 0.2446, 0.0461],
         [0.7737, 0.9193, 0.6260, 0.1214],
         [0.0117, 0.7833, 0.6692, 0.1084]]),
 tensor([[0.0264, 0.9775, 0.4449, 0.3109, 0.7528],
         [0.3279, 0.7904, 0.5625, 0.1013, 0.3399],
         [0.4000, 0.6632, 0.5702, 0.9594, 0.9428],
         [0.8072, 0.0614, 0.3238, 0.0036, 0.6157],
         [0.4995, 0.8749, 0.2871, 0.5104, 0.5305]]))

In [ ]:
# матричные операции

print(a @ b, (a @ b).shape)

print()

print(torch.matmul(a, b), torch.matmul(a, b).shape)

print()

print(c.trace())

print()

print(c.exp())

tensor([[0.5633, 1.1042, 0.9339, 0.1656],
        [0.2658, 0.9576, 0.8598, 0.1459]]) torch.Size([2, 4])

tensor([[0.5633, 1.1042, 0.9339, 0.1656],
        [0.2658, 0.9576, 0.8598, 0.1459]]) torch.Size([2, 4])

tensor(1.9212)

tensor([[1.0268, 2.6579, 1.5603, 1.3647, 2.1229],
        [1.3880, 2.2043, 1.7551, 1.1066, 1.4048],
        [1.4919, 1.9409, 1.7685, 2.6100, 2.5671],
        [2.2417, 1.0633, 1.3823, 1.0036, 1.8509],
        [1.6479, 2.3987, 1.3325, 1.6659, 1.6998]])


### [Автоматическое дифференцирование](https://pytorch.org/docs/stable/notes/autograd.html)

In [ ]:
x = torch.rand(5)

x

tensor([0.7076, 0.3914, 0.9870, 0.3090, 0.6262])

In [ ]:
w = torch.rand(3, 5, requires_grad=True)

w

tensor([[0.3531, 0.4118, 0.7373, 0.5783, 0.4483],
        [0.3005, 0.9868, 0.6453, 0.5094, 0.3786],
        [0.6972, 0.2405, 0.4653, 0.5081, 0.5772]], requires_grad=True)

In [ ]:
print(w.grad)

None


In [ ]:
first_z = torch.empty(3)

first_z

tensor([-1.7320e-12,  3.0774e-41, -1.7366e-12])

In [ ]:
for i in range(3):
    first_z[i] = torch.sum(w[i] * x)

first_z

tensor([1.5983, 1.6304, 1.5652], grad_fn=<CopySlices>)

In [ ]:
z = torch.matmul(x, w.t())

z

tensor([1.5983, 1.6304, 1.5652], grad_fn=<SqueezeBackward3>)

In [ ]:
v = torch.rand(3, requires_grad=True)

v

tensor([0.1148, 0.7261, 0.6116], requires_grad=True)

In [ ]:
print(v.grad)

None


In [ ]:
y = torch.sum(z * v)

y

tensor(2.3244, grad_fn=<SumBackward0>)

In [ ]:
y.item()

2.3244199752807617

In [ ]:
loss = torch.mean((y - 2) ** 2)

In [ ]:
loss

tensor(0.1052, grad_fn=<MeanBackward0>)

In [ ]:
print(f'{x.grad=}\n')
print(f'{w.grad=}\n')
print(f'{z.grad=}\n')
print(f'{v.grad=}\n')

x.grad=None

w.grad=None

z.grad=None

v.grad=None



/home/nuke/.local/lib/python3.10/site-packages/torch/_tensor.py:1083: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at  aten/src/ATen/core/TensorBody.h:477.)
  return self._grad


In [ ]:
loss.backward()

In [ ]:
print(f'{x.grad=}\n')
print(f'{w.grad=}\n')
print(f'{z.grad=}\n')
print(f'{v.grad=}\n')

x.grad=None

w.grad=tensor([[0.0527, 0.0291, 0.0735, 0.0230, 0.0466],
        [0.3334, 0.1844, 0.4650, 0.1456, 0.2950],
        [0.2808, 0.1553, 0.3917, 0.1226, 0.2485]])

z.grad=None

v.grad=tensor([1.0370, 1.0579, 1.0155])



In [ ]:
a = torch.rand(1, requires_grad=True)
b = torch.rand(1, requires_grad=True)

a, b

(tensor([0.5492], requires_grad=True), tensor([0.4124], requires_grad=True))

In [ ]:
loss = (a - b)

loss

tensor([0.1368], grad_fn=<SubBackward0>)

In [ ]:
print(f'{a.grad=}\n')
print(f'{b.grad=}\n')

a.grad=None

b.grad=None



In [ ]:
loss.backward()

In [ ]:
print(f'{a.grad=}\n')  # 1
print(f'{b.grad=}\n')  # -1

a.grad=tensor([2.])

b.grad=tensor([-2.])



In [ ]:
a.grad.zero_()
b.grad.zero_()

tensor([0.])

In [ ]:
loss = (a - b) ** 2

loss

tensor([0.0187], grad_fn=<PowBackward0>)

In [ ]:
print(f'{a.grad=}\n')
print(f'{b.grad=}\n')

a.grad=tensor([0.])

b.grad=tensor([0.])



In [ ]:
loss.backward()

In [ ]:
print(f'{a.grad=}\n')  # 2 * (a - b)
print(f'{b.grad=}\n')  # -2 * (a - b)

a.grad=tensor([0.2736])

b.grad=tensor([-0.2736])



In [ ]:
2 * (a - b)

tensor([0.2736], grad_fn=<MulBackward0>)

In [ ]:
a = torch.rand(3, 5, requires_grad=True)
b = torch.rand(3, 5, requires_grad=True)

a, b

(tensor([[0.3279, 0.5942, 0.6495, 0.8076, 0.6961],
         [0.7243, 0.3865, 0.4297, 0.0069, 0.3211],
         [0.9084, 0.0009, 0.5393, 0.4543, 0.1057]], requires_grad=True),
 tensor([[0.3158, 0.7038, 0.3901, 0.7456, 0.8604],
         [0.4813, 0.8476, 0.9554, 0.9591, 0.9958],
         [0.5856, 0.4295, 0.9476, 0.6895, 0.3585]], requires_grad=True))

In [ ]:
loss = torch.mean(a * b)

loss

tensor(0.3189, grad_fn=<MeanBackward0>)

In [ ]:
print(f'{a.grad=}\n')
print(f'{b.grad=}\n')

a.grad=None

b.grad=None



In [ ]:
loss.backward()

In [ ]:
print(f'{a.grad=}\n')  # b / (3 * 5)
print(f'{b.grad=}\n')  # a / (3 * 5)

a.grad=tensor([[0.0211, 0.0469, 0.0260, 0.0497, 0.0574],
        [0.0321, 0.0565, 0.0637, 0.0639, 0.0664],
        [0.0390, 0.0286, 0.0632, 0.0460, 0.0239]])

b.grad=tensor([[2.1862e-02, 3.9616e-02, 4.3297e-02, 5.3840e-02, 4.6404e-02],
        [4.8289e-02, 2.5765e-02, 2.8644e-02, 4.6089e-04, 2.1404e-02],
        [6.0560e-02, 6.2525e-05, 3.5952e-02, 3.0284e-02, 7.0479e-03]])



In [ ]:
a / 15

tensor([[2.1862e-02, 3.9616e-02, 4.3297e-02, 5.3840e-02, 4.6404e-02],
        [4.8289e-02, 2.5765e-02, 2.8644e-02, 4.6089e-04, 2.1404e-02],
        [6.0560e-02, 6.2525e-05, 3.5952e-02, 3.0284e-02, 7.0479e-03]],
       grad_fn=<DivBackward0>)

In [ ]:
b / 15

tensor([[0.0211, 0.0469, 0.0260, 0.0497, 0.0574],
        [0.0321, 0.0565, 0.0637, 0.0639, 0.0664],
        [0.0390, 0.0286, 0.0632, 0.0460, 0.0239]], grad_fn=<DivBackward0>)

In [ ]:
a = torch.rand(3, 5, requires_grad=True)

print(f'{a=}\n')

loss1 = torch.sum(a ** 2) # 2a
loss2 = torch.sum(a) # 1

print(f'{a.grad=}\n')

loss1.backward()

print(f'{a.grad=}\n')

loss2.backward()

print(f'{a.grad=}\n')

a=tensor([[0.9249, 0.5178, 0.4018, 0.5241, 0.2307],
        [0.4165, 0.5878, 0.6177, 0.4664, 0.3297],
        [0.2164, 0.3102, 0.1307, 0.8902, 0.9583]], requires_grad=True)

a.grad=None

a.grad=tensor([[1.8499, 1.0356, 0.8036, 1.0483, 0.4613],
        [0.8329, 1.1757, 1.2353, 0.9329, 0.6594],
        [0.4329, 0.6204, 0.2613, 1.7805, 1.9166]])

a.grad=tensor([[2.8499, 2.0356, 1.8036, 2.0483, 1.4613],
        [1.8329, 2.1757, 2.2353, 1.9329, 1.6594],
        [1.4329, 1.6204, 1.2613, 2.7805, 2.9166]])



In [ ]:
print(f'{2*a=}\n')
print(f'{2*a+1=}')

2*a=tensor([[1.8499, 1.0356, 0.8036, 1.0483, 0.4613],
        [0.8329, 1.1757, 1.2353, 0.9329, 0.6594],
        [0.4329, 0.6204, 0.2613, 1.7805, 1.9166]], grad_fn=<MulBackward0>)

2*a+1=tensor([[2.8499, 2.0356, 1.8036, 2.0483, 1.4613],
        [1.8329, 2.1757, 2.2353, 1.9329, 1.6594],
        [1.4329, 1.6204, 1.2613, 2.7805, 2.9166]], grad_fn=<AddBackward0>)


In [ ]:
a = torch.rand(3, 5, requires_grad=True)
b = torch.rand(3, 5, requires_grad=False)

a, b

(tensor([[0.9585, 0.8137, 0.7837, 0.3117, 0.5308],
         [0.5991, 0.7310, 0.9645, 0.7374, 0.7492],
         [0.5522, 0.8426, 0.0137, 0.8135, 0.0080]], requires_grad=True),
 tensor([[0.0779, 0.3624, 0.0938, 0.1770, 0.2233],
         [0.3437, 0.3984, 0.9332, 0.7502, 0.0515],
         [0.3722, 0.6910, 0.0804, 0.5425, 0.1549]]))

In [ ]:
loss = torch.sum(a - b)

loss

tensor(4.1571, grad_fn=<SumBackward0>)

In [ ]:
print(f'{a.grad=}\n')
print(f'{b.grad=}\n')

a.grad=None

b.grad=None



In [ ]:
loss.backward()

In [ ]:
print(f'{a.grad=}\n')  # all ones
print(f'{b.grad=}\n')  # None

a.grad=tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

b.grad=None



In [ ]:
a = torch.rand(3, 5, requires_grad=True)
b = torch.rand(3, 5, requires_grad=True)

a, b

(tensor([[0.4873, 0.0094, 0.3410, 0.6388, 0.3698],
         [0.3318, 0.3989, 0.4540, 0.8396, 0.7872],
         [0.2356, 0.5495, 0.3216, 0.0462, 0.1471]], requires_grad=True),
 tensor([[0.9219, 0.8603, 0.0196, 0.7148, 0.3156],
         [0.4160, 0.4039, 0.9161, 0.9858, 0.4589],
         [0.9566, 0.1626, 0.5449, 0.9074, 0.7661]], requires_grad=True))

In [ ]:
with torch.no_grad():
    loss = torch.sum(a - b)

loss

tensor(-3.3924)

In [ ]:
loss.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [ ]:
a = torch.rand(3, 5, requires_grad=True)
b = torch.rand(3, 5, requires_grad=True)

a, b

(tensor([[0.4194, 0.7270, 0.6554, 0.8120, 0.2465],
         [0.3338, 0.5301, 0.4804, 0.7732, 0.9213],
         [0.9066, 0.9495, 0.0488, 0.6136, 0.7182]], requires_grad=True),
 tensor([[0.2233, 0.5705, 0.0119, 0.8199, 0.7503],
         [0.4163, 0.5326, 0.9683, 0.9022, 0.6971],
         [0.3597, 0.9322, 0.4627, 0.8851, 0.0571]], requires_grad=True))

In [ ]:
with torch.inference_mode():
    loss = torch.sum(a - b)

loss

tensor(0.5469)

In [ ]:
loss.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [ ]:
with torch.no_grad():
    a = torch.rand(3, 5, requires_grad=True)
    b = torch.rand(3, 5, requires_grad=True)
    
    loss = torch.sum(a + b)
    
    print(f'{loss=}')
    
    loss.backward()

loss=tensor(15.7352)


RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [ ]:
loss2 = torch.sum(a + b)

loss2

tensor(15.7352, grad_fn=<SumBackward0>)

In [ ]:
print(f'{a.grad=}\n')
print(f'{b.grad=}\n')

a.grad=None

b.grad=None



In [ ]:
loss2.backward()

In [ ]:
print(f'{a.grad=}\n')
print(f'{b.grad=}\n')

a.grad=tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

b.grad=tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])



In [ ]:
with torch.inference_mode():
    a = torch.rand(3, 5, requires_grad=True)
    b = torch.rand(3, 5, requires_grad=True)
    
    loss = torch.sum(a + b)
    
    print(f'{loss=}')
    
    loss.backward()

loss=tensor(19.4477)


RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [ ]:
loss2 = torch.sum(a + b)

loss2

tensor(19.4477)

In [ ]:
@torch.no_grad()
def foo():
    a = torch.rand(3, 5, requires_grad=True)
    b = torch.rand(3, 5, requires_grad=True)
    
    loss = torch.mean(a + b)
    
    print(f'{loss=}')
    
    return a, b

In [ ]:
a, b = foo()

loss=tensor(0.9730)


In [ ]:
torch.mean(a - b)

tensor(0.0091, grad_fn=<MeanBackward0>)

In [ ]:
@torch.inference_mode()
def foo():
    a = torch.rand(3, 5, requires_grad=True)
    b = torch.rand(3, 5, requires_grad=True)
    
    loss = torch.mean(a + b)
    
    print(f'{loss=}')
    
    return a, b

In [ ]:
a, b = foo()

loss=tensor(1.0910)


In [ ]:
torch.mean(a - b)

tensor(0.0245)

In [ ]:
a.requires_grad = False

## Полносвязные слои и функции активации в `PyTorch`

In [ ]:
from torch import nn

### Полносвязный слой

>$y_j = \sum\limits_{i=1}^{n}x_iw_{ji} + b_j$


In [ ]:
layer = nn.Linear(in_features=5, out_features=3)

In [ ]:
layer

Linear(in_features=5, out_features=3, bias=True)

In [ ]:
layer.weight

Parameter containing:
tensor([[ 0.1036, -0.0857,  0.1891,  0.1899,  0.0061],
        [-0.2206, -0.1663, -0.0230, -0.0566, -0.0549],
        [-0.1880, -0.2969, -0.1313,  0.2695,  0.4457]], requires_grad=True)

In [ ]:
layer.weight.shape

torch.Size([3, 5])

In [ ]:
layer.bias

Parameter containing:
tensor([ 0.1110, -0.0980, -0.0736], requires_grad=True)

In [ ]:
layer = nn.Linear(in_features=5, out_features=3, bias=False)

In [ ]:
layer.bias

In [ ]:
layer.__call__

In [ ]:
x = torch.randn(5)

print(layer(x))

tensor([-0.3352,  0.3743,  0.8121], grad_fn=<SqueezeBackward3>)


### Функции активации

> Сигмоида $f(x) = \dfrac{1}{1 + e^{-x}}$

In [ ]:
activation = nn.Sigmoid()

In [ ]:
x = torch.randn(5)

print(x)

print(activation(x))

tensor([-1.7887, -2.3923,  0.1006, -1.6202,  1.0863])
tensor([0.1432, 0.0838, 0.5251, 0.1652, 0.7477])


> ReLU $f(x) = \max(0, x)$

In [ ]:
activation = nn.ReLU()

In [ ]:
x = torch.randn(5)

print(x)

print(activation(x))

tensor([-0.6977,  0.5788, -1.0462, -0.7537,  0.8037])
tensor([0.0000, 0.5788, 0.0000, 0.0000, 0.8037])


> Leaky ReLU $f(x) = \max(0, x) + \alpha \min(0, x)$

In [ ]:
activation = nn.LeakyReLU(negative_slope=0.001)

In [ ]:
x = torch.randn(5)

print(x)

print(activation(x))

tensor([ 1.4079, -0.8732,  0.4297,  0.5221,  0.3086])
tensor([ 1.4079e+00, -8.7321e-04,  4.2974e-01,  5.2209e-01,  3.0863e-01])


## Градиентный спуск своими руками

In [ ]:
n_features = 2
n_objects = 300

torch.manual_seed(0)

w_true = torch.randn(n_features)
b_true = torch.randn(1)

x = (torch.rand(n_objects, n_features) - 0.5) * 10 * (torch.arange(n_features) * 2 + 1)
y = torch.matmul(x, w_true) + torch.randn(n_objects) + b_true

In [ ]:
n_steps = 200
step_size = 1e-2

In [ ]:
w = torch.rand(n_features, requires_grad=True)
b = torch.rand(1, requires_grad=True)

for i in range(n_steps):
    y_pred = torch.matmul(x, w) + b
    
    mse = torch.mean((y_pred - y) ** 2)
    
    if i < 20 or i % 10 == 0:
        print(f'MSE на шаге {i + 1} {mse.item():.5f}')

    mse.backward()

    with torch.no_grad():
        w -= w.grad * step_size
        b -= b.grad * step_size

    w.grad.zero_()
    b.grad.zero_()

MSE на шаге 1 23.65750
MSE на шаге 2 15.53605
MSE на шаге 3 12.11575
MSE на шаге 4 10.36995
MSE на шаге 5 9.30175
MSE на шаге 6 8.55659
MSE на шаге 7 7.99169
MSE на шаге 8 7.53972
MSE на шаге 9 7.16377
MSE на шаге 10 6.84131
MSE на шаге 11 6.55765
MSE на шаге 12 6.30292
MSE на шаге 13 6.07033
MSE на шаге 14 5.85515
MSE на шаге 15 5.65409
MSE на шаге 16 5.46479
MSE на шаге 17 5.28555
MSE на шаге 18 5.11514
MSE на шаге 19 4.95265
MSE на шаге 20 4.79735
MSE на шаге 21 4.64871
MSE на шаге 31 3.45555
MSE на шаге 41 2.65631
MSE на шаге 51 2.11964
MSE на шаге 61 1.75925
MSE на шаге 71 1.51724
MSE на шаге 81 1.35471
MSE на шаге 91 1.24558
MSE на шаге 101 1.17229
MSE на шаге 111 1.12307
MSE на шаге 121 1.09002
MSE на шаге 131 1.06782
MSE на шаге 141 1.05292
MSE на шаге 151 1.04291
MSE на шаге 161 1.03619
MSE на шаге 171 1.03168
MSE на шаге 181 1.02864
MSE на шаге 191 1.02661


In [ ]:
layer = nn.Linear(in_features=n_features, out_features=1)

for i in range(n_steps):
    y_pred = layer(x)

    mse = torch.mean((y_pred - y) ** 2)
    
    if i < 20 or i % 10 == 0:
        print(f'MSE на шаге {i + 1} {mse.item():.5f}')

    mse.backward()

    with torch.no_grad():
        layer.weight -= layer.weight.grad * step_size
        layer.bias -= layer.bias.grad * step_size

#     layer.weight.grad.zero_()
#     layer.bias.grad.zero_()
    
    layer.zero_grad()

MSE на шаге 1 67.76115
MSE на шаге 2 42.90440
MSE на шаге 3 34.78294
MSE на шаге 4 31.90576
MSE на шаге 5 30.72448
MSE на шаге 6 30.12742
MSE на шаге 7 29.75548
MSE на шаге 8 29.48539
MSE на шаге 9 29.27014
MSE на шаге 10 29.08890
MSE на шаге 11 28.93083
MSE на шаге 12 28.78951
MSE на шаге 13 28.66082
MSE на шаге 14 28.54199
MSE на шаге 15 28.43109
MSE на шаге 16 28.32677
MSE на шаге 17 28.22807
MSE на шаге 18 28.13428
MSE на шаге 19 28.04487
MSE на шаге 20 27.95945
MSE на шаге 21 27.87770
MSE на шаге 31 27.22173
MSE на шаге 41 26.78238
MSE на шаге 51 26.48738
MSE на шаге 61 26.28927
MSE на шаге 71 26.15623
MSE на шаге 81 26.06689
MSE на шаге 91 26.00690
MSE на шаге 101 25.96661
MSE на шаге 111 25.93955
MSE на шаге 121 25.92138
MSE на шаге 131 25.90918
MSE на шаге 141 25.90099
MSE на шаге 151 25.89549
MSE на шаге 161 25.89179
MSE на шаге 171 25.88931
MSE на шаге 181 25.88764
MSE на шаге 191 25.88653


In [ ]:
layer(x)

tensor([[-2.7298],
        [-2.7292],
        [-2.7318],
        [-2.7311],
        [-2.7278],
        [-2.7308],
        [-2.7292],
        [-2.7330],
        [-2.7296],
        [-2.7168],
        [-2.7313],
        [-2.7349],
        [-2.7305],
        [-2.7286],
        [-2.7363],
        [-2.7269],
        [-2.7251],
        [-2.7222],
        [-2.7308],
        [-2.7260],
        [-2.7310],
        [-2.7279],
        [-2.7256],
        [-2.7202],
        [-2.7229],
        [-2.7306],
        [-2.7265],
        [-2.7337],
        [-2.7233],
        [-2.7287],
        [-2.7279],
        [-2.7318],
        [-2.7289],
        [-2.7257],
        [-2.7223],
        [-2.7243],
        [-2.7390],
        [-2.7176],
        [-2.7257],
        [-2.7269],
        [-2.7223],
        [-2.7276],
        [-2.7244],
        [-2.7321],
        [-2.7252],
        [-2.7309],
        [-2.7242],
        [-2.7299],
        [-2.7348],
        [-2.7298],
        [-2.7290],
        [-2.7337],
        [-2.

In [ ]:
layer(x).shape

torch.Size([300, 1])

In [ ]:
y.shape

torch.Size([300])

In [ ]:
(layer(x) - y).shape

torch.Size([300, 300])

In [ ]:
(layer(x).ravel() - y).shape

torch.Size([300])

In [ ]:
layer = nn.Linear(in_features=n_features, out_features=1)

for i in range(n_steps):
    y_pred = layer(x).ravel()

    mse = torch.mean((y_pred - y) ** 2)
    
    if i < 20 or i % 10 == 0:
        print(f'MSE на шаге {i + 1} {mse.item():.5f}')

    mse.backward()

    with torch.no_grad():
        layer.weight -= layer.weight.grad * step_size
        layer.bias -= layer.bias.grad * step_size

    layer.zero_grad()

MSE на шаге 1 82.40031
MSE на шаге 2 34.83059
MSE на шаге 3 18.67639
MSE на шаге 4 12.57786
MSE на шаге 5 9.87140
MSE на шаге 6 8.42349
MSE на шаге 7 7.51441
MSE на шаге 8 6.87739
MSE на шаге 9 6.39865
MSE на шаге 10 6.02125
MSE на шаге 11 5.71254
MSE на шаге 12 5.45201
MSE на шаге 13 5.22616
MSE на шаге 14 5.02584
MSE на шаге 15 4.84476
MSE на шаге 16 4.67857
MSE на шаге 17 4.52421
MSE на шаге 18 4.37955
MSE на шаге 19 4.24304
MSE на шаге 20 4.11358
MSE на шаге 21 3.99035
MSE на шаге 31 3.01138
MSE на шаге 41 2.35799
MSE на шаге 51 1.91931
MSE на шаге 61 1.62472
MSE на шаге 71 1.42689
MSE на шаге 81 1.29405
MSE на шаге 91 1.20484
MSE на шаге 101 1.14493
MSE на шаге 111 1.10470
MSE на шаге 121 1.07768
MSE на шаге 131 1.05954
MSE на шаге 141 1.04736
MSE на шаге 151 1.03917
MSE на шаге 161 1.03368
MSE на шаге 171 1.02999
MSE на шаге 181 1.02751
MSE на шаге 191 1.02585


In [ ]:
n_features = 5
n_objects = 300

torch.manual_seed(0)

w_true = torch.randn(n_features)

x = (torch.rand(n_objects, n_features) - 0.5) * 10 * (torch.arange(n_features) * 2 + 1)
y = torch.matmul(x, w_true) + torch.randn(n_objects)

In [ ]:
n_steps = 2000
step_size = 1e-3

In [ ]:
layer = nn.Linear(in_features=n_features, out_features=1)

for i in range(n_steps):
    y_pred = layer(x).ravel()

    mse = torch.mean((y_pred - y) ** 2)
    
    if i < 20 or i % 50 == 0:
        print(f'MSE на шаге {i + 1} {mse.item():.5f}')

    mse.backward()

    with torch.no_grad():
        layer.weight -= layer.weight.grad * step_size
        layer.bias -= layer.bias.grad * step_size

    layer.zero_grad()

MSE на шаге 1 2052.12988
MSE на шаге 2 606.21967
MSE на шаге 3 207.55234
MSE на шаге 4 82.47279
MSE на шаге 5 40.03379
MSE на шаге 6 24.82249
MSE на шаге 7 19.02928
MSE на шаге 8 16.58483
MSE на шаге 9 15.35648
MSE на шаге 10 14.58259
MSE на шаге 11 13.98817
MSE на шаге 12 13.47272
MSE на шаге 13 12.99872
MSE на шаге 14 12.55160
MSE на шаге 15 12.12528
MSE на шаге 16 11.71682
MSE на шаге 17 11.32460
MSE на шаге 18 10.94749
MSE на шаге 19 10.58467
MSE на шаге 20 10.23542
MSE на шаге 51 3.92278
MSE на шаге 101 1.43192
MSE на шаге 151 1.02777
MSE на шаге 201 0.95445
MSE на шаге 251 0.93498
MSE на шаге 301 0.92541
MSE на шаге 351 0.91856
MSE на шаге 401 0.91310
MSE на шаге 451 0.90864
MSE на шаге 501 0.90498
MSE на шаге 551 0.90198
MSE на шаге 601 0.89951
MSE на шаге 651 0.89748
MSE на шаге 701 0.89582
MSE на шаге 751 0.89445
MSE на шаге 801 0.89333
MSE на шаге 851 0.89241
MSE на шаге 901 0.89165
MSE на шаге 951 0.89103
MSE на шаге 1001 0.89052
MSE на шаге 1051 0.89010
MSE на шаге 1101 0.8

In [ ]:
n_steps = 2000
step_size = 5e-4

In [ ]:
layer1 = nn.Linear(in_features=n_features, out_features=3)
layer2 = nn.Linear(in_features=3, out_features=1)
activation = nn.ReLU()


for i in range(n_steps):
    y_pred = layer2(activation(layer1(x))).ravel()

    mse = torch.mean((y_pred - y) ** 2)

    if i < 20 or i % 50 == 0:
        print(f'MSE на шаге {i + 1} {mse.item():.5f}')

    mse.backward()

    with torch.no_grad():
        layer1.weight -= layer1.weight.grad * step_size
        layer1.bias -= layer1.bias.grad * step_size
        layer2.weight -= layer2.weight.grad * step_size
        layer2.bias -= layer2.bias.grad * step_size

    layer1.zero_grad()
    layer2.zero_grad()

MSE на шаге 1 1942.53650
MSE на шаге 2 1676.33215
MSE на шаге 3 1462.73621
MSE на шаге 4 1252.29272
MSE на шаге 5 1084.68542
MSE на шаге 6 969.74554
MSE на шаге 7 892.42969
MSE на шаге 8 837.99945
MSE на шаге 9 791.54950
MSE на шаге 10 736.85345
MSE на шаге 11 660.66931
MSE на шаге 12 552.94324
MSE на шаге 13 420.34772
MSE на шаге 14 295.80695
MSE на шаге 15 213.59764
MSE на шаге 16 170.35097
MSE на шаге 17 140.10820
MSE на шаге 18 116.49634
MSE на шаге 19 95.18255
MSE на шаге 20 74.59748
MSE на шаге 51 9.93147
MSE на шаге 101 3.76550
MSE на шаге 151 1.81388
MSE на шаге 201 1.21714
MSE на шаге 251 1.03567
MSE на шаге 301 0.97787
MSE на шаге 351 0.95785
MSE на шаге 401 0.94890
MSE на шаге 451 0.94261
MSE на шаге 501 0.93729
MSE на шаге 551 0.93249
MSE на шаге 601 0.92810
MSE на шаге 651 0.92405
MSE на шаге 701 0.92031
MSE на шаге 751 0.91686
MSE на шаге 801 0.91367
MSE на шаге 851 0.91071
MSE на шаге 901 0.90798
MSE на шаге 951 0.90545
MSE на шаге 1001 0.90310
MSE на шаге 1051 0.90093
M